//
//  listMoviePresenter.swift
//  MovieApp
//
//  Created by Ilham on 21/02/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol listMoviePresentationLogic {
    func presentMovie(movieArray: [MovieModels])
    func presentMoreMovie(movieArray: [MovieModels])
}

class listMoviePresenter: listMoviePresentationLogic {
    weak var viewController: listMovieDisplayLogic?
    
    func presentMovie(movieArray: [MovieModels]) {
        let viewModel = movieArray.map{
            listMovieTableViewCell.ViewModel(idMovie: $0.id!, movieThumbnailURL: $0.thumbnail!, movieTitle: $0.title!, movieReleaseDate: $0.releaseDate!, movieOverview: $0.overview!)
        }
        viewController?.displayMovie(movie: viewModel)
    }
    
    func presentMoreMovie(movieArray: [MovieModels]) {
        let viewModel = movieArray.map{
            listMovieTableViewCell.ViewModel(idMovie: $0.id!, movieThumbnailURL: $0.thumbnail!, movieTitle: $0.title!, movieReleaseDate: $0.releaseDate!, movieOverview: $0.overview!)
        }
        viewController?.displayMoreMovie(movie: viewModel)
    }
}
