//
//  listMovieModels.swift
//  MovieApp
//
//  Created by Ilham on 21/02/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ObjectMapper

class MovieModels: Mappable {
    var id: Int?
    var title: String?
    var releaseDate: String?
    var overview: String?
    var thumbnail: String?
    
    required init?(map: Map) {
        mapping(map: map)
    }
    
    func mapping(map: Map) {
        id <- map["id"]
        title <- map["title"]
        releaseDate <- map["release_date"]
        overview <- map["overview"]
        thumbnail <- map["poster_path"]
    }
}
