//
//  detailMoviePresenter.swift
//  MovieApp
//
//  Created by Ilham on 21/02/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol detailMoviePresentationLogic {
    func presentMovieReview(movieReview: [MovieReviewModel])
    func presentSuccess(message: String)
    func presentError(message: String)
    func presentDuplicateMovie()
}

class detailMoviePresenter: detailMoviePresentationLogic {
    weak var viewController: detailMovieDisplayLogic?

    func presentMovieReview(movieReview: [MovieReviewModel]) {
        let viewModel = movieReview.map {
            listMovieReviewTableViewCell.ViewModel(author: $0.author!, content: $0.content!)
        }
        
        viewController?.displayReviewMovie(movieReview: viewModel )
    }
    
    func presentSuccess(message: String) {
        viewController?.displaySuccess(message: message)
    }
    
    func presentError(message: String) {
        viewController?.displayError(message: message)
    }
    
    func presentDuplicateMovie() {
        viewController?.displayDuplicateMovie()
    }
    
}
