//
//  listMovieViewControllerTests.swift
//  MovieApp
//
//  Created by Ilham on 22/02/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MovieApp
import XCTest

class listMovieViewControllerTests: XCTestCase {
    class listMovieInteractorMock: listMovieBusinessLogic {
        var requestMovieDataCalled = false
        var loadMoreDataCalled = false
        
        func requestMovieData(withFilter: MovieAppConstants.FilterType) {
            requestMovieDataCalled = true
        }
        
        func loadMoreData() {
            loadMoreDataCalled = true
        }
    }
    
    var vc: listMovieViewController!
    var interactor: listMovieInteractorMock!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setuplistMovieViewController()
        interactor = listMovieInteractorMock()
        
        vc.interactor = interactor
    }
    
    override func tearDown() {
        window = nil
        vc = nil
        interactor = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setuplistMovieViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "listMovie", bundle: bundle)
        vc = storyboard.instantiateViewController(withIdentifier: "listMovie") as? listMovieViewController
    }
    
    func loadView() {
        window.addSubview(vc.view)
        RunLoop.current.run(until: Date())
    }
    
    func testRequestMoviewData() {
        //when
        loadView()
        
        //then
        XCTAssert(interactor.requestMovieDataCalled, "requestMovieData should be called")
    }
    
    func testLoadMoreMovieData() {
        //given
        let indexPath = IndexPath(row: 0, section: 0)
        vc.listMovieTableView = UITableView()
        loadView()
        
        //when
        vc.displayMovie(movie: [MovieAppTestConstant.listMovieDataStub])
        let _ = vc.tableView(vc.listMovieTableView, cellForRowAt: indexPath)
        
        //then
        XCTAssert(interactor.loadMoreDataCalled, "loadMoreData should be called")
    }
    
}
