//
//  listMoviePresenterTests.swift
//  MovieApp
//
//  Created by Ilham on 22/02/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MovieApp
import XCTest

class listMoviePresenterTests: XCTestCase {
    class listMovieViewControllerMock: listMovieDisplayLogic {
        var displayMovieCalled = false
        var displayMoreMovieCalled = false
        
        func displayMovie(movie: [listMovieTableViewCell.ViewModel]) {
            displayMovieCalled = true
        }
        
        func displayMoreMovie(movie: [listMovieTableViewCell.ViewModel]) {
            displayMoreMovieCalled = true
        }
    }
    
    var presenter: listMoviePresenter!
    var viewController: listMovieViewControllerMock!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        presenter = listMoviePresenter()
        viewController = listMovieViewControllerMock()
        
        presenter.viewController = viewController
    }
    
    override func tearDown() {
        presenter = nil
        viewController = nil
        super.tearDown()
    }
    
    func testPresentMovie() {
        //when
        presenter.presentMovie(movieArray: [MovieAppTestConstant.movieModelStub])
        
        //then
        XCTAssert(viewController.displayMovieCalled,"displayMovie should be called")
    }
    
    func testPresentMoreMovie() {
        //when
        presenter.presentMoreMovie(movieArray: [MovieAppTestConstant.movieModelStub])
        
        //then
        XCTAssert(viewController.displayMoreMovieCalled,"displayMoreMovie should be called")
    }
    
}
