//
//  favouriteMovieViewControllerTests.swift
//  MovieApp
//
//  Created by Ilham on 23/02/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MovieApp
import XCTest

class favouriteMovieViewControllerTests: XCTestCase {
    class favouriteMovieInteractorMock: favouriteMovieBusinessLogic {
        var getLocalMovieDataCalled = false
        
        func getLocalMovieData() {
            getLocalMovieDataCalled = true
        }
    }
    
    var vc: favouriteMovieViewController!
    var interactor: favouriteMovieInteractorMock!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        vc = favouriteMovieViewController.instantiate()
        interactor = favouriteMovieInteractorMock()
        
        vc.interactor = interactor
    }
    
    override func tearDown() {
        window = nil
        vc = nil
        interactor = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func loadView() {
        window.addSubview(vc.view)
        RunLoop.current.run(until: Date())
    }
    
    func testGetLocalMovieData() {
        //when
        vc.beginAppearanceTransition(true, animated: true)
        
        //then
        XCTAssert(interactor.getLocalMovieDataCalled, "getLocalMovieData should be called")
    }
}
