//
//  favouriteMoviePresenterTests.swift
//  MovieApp
//
//  Created by Ilham on 23/02/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MovieApp
import XCTest

class favouriteMoviePresenterTests: XCTestCase {
    class favouriteMovieViewControllerMock: favouriteMovieDisplayLogic {
        var displaySavedMovieDataCalled = false
        var displayErrorCalled = false
        
        func displaySavedMovieData(localMovieModel: [listMovieTableViewCell.ViewModel]) {
            displaySavedMovieDataCalled = true
        }
        
        func displayError(message: String) {
            displayErrorCalled = true
        }
    }
    
    var presenter: favouriteMoviePresenter!
    var vc: favouriteMovieViewControllerMock!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        presenter = favouriteMoviePresenter()
        vc = favouriteMovieViewControllerMock()
        
        presenter.viewController = vc
    }
    
    override func tearDown() {
        presenter = nil
        vc = nil
        super.tearDown()
    }
    
    func testPresentLocalDataMovie() {
        //when
        presenter.presentLocalDataMovie(model: [MovieAppTestConstant.listMovieDataStub])
        
        //then
        XCTAssert(vc.displaySavedMovieDataCalled, "displaySavedMovieData should be called")
    }
    
    func testPresentError() {
        //when
        presenter.presentError(message: "error")
        
        //then
        XCTAssert(vc.displayErrorCalled, "displayError should be called")
    }
}
