//
//  favouriteMovieInteractor.swift
//  MovieApp
//
//  Created by Ilham on 21/02/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol favouriteMovieBusinessLogic {
    func getLocalMovieData()
}

class favouriteMovieInteractor: favouriteMovieBusinessLogic {
    var presenter: favouriteMoviePresentationLogic?
    
    func getLocalMovieData() {
        if let data = UserDefaults.standard.value(forKey: MovieAppConstants.MovieUserDefault.movie) as? Data {
            let localMovie = try? PropertyListDecoder().decode(Array<listMovieTableViewCell.ViewModel>.self, from: data)
            if localMovie?.count == .zero {
                presenter?.presentError(message: MovieAppConstants.Message.Error.savedMovieNotFound)
            } else {
                presenter?.presentLocalDataMovie(model: localMovie!)
            }
        } else {
            presenter?.presentError(message: MovieAppConstants.Message.Error.savedMovie)
        }
    }
}
