//
//  favouriteMoviePresenter.swift
//  MovieApp
//
//  Created by Ilham on 21/02/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol favouriteMoviePresentationLogic {
    func presentLocalDataMovie(model: [listMovieTableViewCell.ViewModel])
    func presentError(message: String)
}

class favouriteMoviePresenter: favouriteMoviePresentationLogic {
    weak var viewController: favouriteMovieDisplayLogic?
    
    func presentLocalDataMovie(model: [listMovieTableViewCell.ViewModel]) {
        viewController?.displaySavedMovieData(localMovieModel: model)
    }
    
    func presentError(message: String) {
        viewController?.displayError(message: message)
    }
}
